# inventory/aws_ec2.yml
plugin: aws_ec2
regions:
  - ap-northeast-2  # 한국 리전
filters:
  instance-state-name: running  # 실행 중인 인스턴스만 포함
keyed_groups:
  - key: tags.Role  # Role 태그를 기준으로 그룹화 (backend, frontend, ai)
    prefix: role
hostnames:
  - tag:Name  # 인스턴스 이름을 호스트명으로 사용
compose:
  ansible_host: public_ip_address  # Ansible이 연결할 IP