name: Create Jira Issue

on:
  issues:
    types: [opened]  # GitHub에서 이슈가 생성될 때 트리거

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
        run: |
          curl -X POST -u $JIRA_USER:$JIRA_TOKEN \
          --data '{
            "fields": {
              "project": {
                "key": "YOUR_PROJECT_KEY"
              },
              "summary": "${{ github.event.issue.title }}",  # GitHub 이슈 제목 사용
              "description": "${{ github.event.issue.body }}",  # GitHub 이슈 본문 사용
              "issuetype": {
                "name": "Bug"  # 이슈 타입을 고정 또는 변경 가능
              }
            }
          }' -H "Content-Type: application/json" \
          $JIRA_URL/rest/api/2/issue/
