name: Create Jira Issue

on:
  workflow_dispatch:
    inputs:
      issuetype:
        description: 'Type of the Jira issue (e.g., Task, Doc, Bug, Epic)'
        required: true
        default: 'Task'  # 기본값 설정

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
        run: |
          curl -X POST -u $JIRA_USER:$JIRA_TOKEN \
          --data '{
            "fields": {
              "project": {
                "key": "YOUR_PROJECT_KEY"
              },
              "summary": "${{ github.event.inputs.issuetype }} Issue from GitHub Actions",  # 이슈 타입을 제목에 포함
              "description": "This issue was automatically created by GitHub Actions.",
              "issuetype": {
                "name": "${{ github.event.inputs.issuetype }}"  # 선택한 이슈 유형 사용
              },
              "priority": {
                "name": "High"  # 우선순위 설정
              }
            }
          }' -H "Content-Type: application/json" \
          $JIRA_URL/rest/api/2/issue/
